#
#
#
# cb = {"id": "3524385852852694030",
#       "from": {"id": 820585026,
#                "is_bot": false,
#                "first_name": "Eugene",
#                "last_name": "Lavrenko",
#                "username": "Perihelion_it",
#                "language_code": "ru"},
#       "message": {"message_id": 297,
#                   "from": {"id": 5577156730,
#                            "is_bot": true,
#                            "first_name": "Джон Сига",
#                            "username": "devlev_NSFW_Bot"},
#                   "chat": {"id": 820585026,
#                            "first_name": "Eugene",
#                            "last_name": "Lavrenko",
#                            "username": "Perihelion_it",
#                            "type": "private"},
#                   "date": 1659007153,
#                   "reply_to_message": {"message_id": 296,
#                                        "from": {"id": 5577156730,
#                                                 "is_bot": true,
#                                                 "first_name": "Джон Сига",
#                                                 "username": "devlev_NSFW_Bot"},
#                                        "chat": {"id": 820585026,
#                                                 "first_name": "Eugene",
#                                                 "last_name": "Lavrenko",
#                                                 "username": "Perihelion_it",
#                                                 "type": "private"},
#                                        "date": 1659007150,
#                                        "text": "Выбор расписания",
#                                        "reply_markup": {"inline_keyboard": [[{"text": "Эта неделя",
#                                                                               "callback_data": "week1"},
#                                                                              {"text": "Следующая неделя",
#                                                                               "callback_data": "week2"}]]}},
#                   "text": "Выберите день:",
#                   "reply_markup": {"inline_keyboard": [[{"text": "Пн-07-25", "callback_data": "day_1"},
#                                                         {"text": "Вт-07-26", "callback_data": "day_2"},
#                                                         {"text": "Ср-07-27", "callback_data": "day_3"}],
#                                                        [{"text": "Чт-07-28", "callback_data": "day_4"},
#                                                         {"text": "Пт-07-29", "callback_data": "day_5"},
#                                                         {"text": "Назад", "callback_data": "day_0"}]]}},
#       "chat_instance": "717619463786866456", "data": "day_5"}
